/**
 * The build-time plugin registry, generated by `src/mod/build/vitePluginMod.ts`.
 */
declare module '~modplugins' {
  import type { Plugin } from '../api/types';

  const plugins: Record<string, Plugin>;
  export default plugins;

  export const PluginMeta: Record<string, { path: string; userPlugin: boolean }>;
}
